apiVersion: v1
kind: Service
metadata:
  name: back-office-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
  labels:
    env: dev
spec:
  selector:
    app: back-office-app
