apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-office-app
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: back-office-app
  template:
    metadata:
      labels:
        app: back-office-app
      spec:
      containers:
      - name: back-office-app
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi