apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app
  labels:
    app: ai-app
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
      - name: ai-app
        image: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/flask/ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name : DEBUG
          value : "False"
        - name : LANGCHAIN_TRACING_V2
          value: "true"
        - name : PINECONE_API_ENV
          value: "gcp-starter"
        - name : FLASK_APP
          value : myenv/app.py
        - name : PINECONE_API_ENV
          value : gcp-starter
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef: 
              key: openapi-key
              name: curi-secret
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef: 
              key: pinecon-key
              name: curi-secret
        - name: SERPAPI_API_KEY
          valueFrom:
            secretKeyRef: 
              key: serpapi-key
              name: curi-secret
        - name: LANGCHAIN_ENDPOINT
          value: "https://api.smith.langchain.com"
        - name: LANGCHAIN_API_KEY
          valueFrom:
            secretKeyRef: 
              key: langchain-api-key
              name: curi-secret
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 768Mi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]