apiVersion: v1
kind: Service
metadata:
  name: ai-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
spec:
  type: NodePort
  selector:
    app: ai-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
