apiVersion: locust.io/v1 
kind: LocustTest 
metadata:
  name: demo.test 
spec:
  image: locustio/locust:latest 
  masterCommandSeed: 
    --locustfile /lotest/src/demo_test.py
    --host https://dummy.restapiexample.com
    --users 100
    --spawn-rate 3
    --run-time 3m
  workerCommandSeed: --locustfile /lotest/src/demo_test.py 
  workerReplicas: 3 
  configMap: demo-test-map 
