apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
