apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.21.0"
    spec:
      volumes: 
      - name: datadog-apm-agent 
        emptyDir: {}
      containers:
      - name: backend-app
        volumeMounts:
        - name: datadog-apm-agent 
          mountPath: /datadog/apm/agent
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_SERVICE
          value: "backend-app"
        - name: DD_ENV
          value: "develop"
        - name: DD_VERSION
          value: "1.0"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_APPSEC_ENABLED
          value: "true"
        - name: DD_TRACE_SAMPLE_RATE
          value: "1"
        - name: DD_JMXFETCH_ENABLED
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: JAVA_OPTS
          value: "-javaagent:/datadog/apm/agent/dd-java-agent.jar"
      initContainers:
      - name: datadog-apm-agent
        image: busybox
        command:
        - wget
        - -O
        - /datadog/apm/agent/dd-java-agent.jar
        - https://dtdg.co/java-tracer-v1 #https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/1.9.0/dd-java-agent-1.9.0.jar
        volumeMounts:
        - name: datadog-apm-agent
          mountPath: /datadog/apm/agent