apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    site : "us5.datadoghq.com"
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
    liveProcessCollection:
      enabled: true
    logCollection:
      enabled: true
    admissionController:
      enabled: true
    externalMetricsServer:
      enabled: true
    cspm:
      enabled: true
    cws:
      enabled: true
    orchestratorExplorer:
      enabled: true