apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
