apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  # annotations:
  #   alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
  labels:
    env: dev
spec:
  selector:
    app: auth-app
