apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curi-demo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/RIDEAT/curi-manifests'
    targetRevision: main
    path: k8s_manifests/demo/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-work
  syncPolicy:
    automated: {}