apiVersion: v1
kind: Service
metadata:
  name: backend-debug-service
  namespace: eks-work
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 30005
    targetPort: 5005
