apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
