apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/spring/curi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: RDS_URL
          valueFrom:
            secretKeyRef: 
              name: rds-url
              key: curi-secret
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef: 
              name: rds-username
              key: curi-secret
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: rds-password
              key: curi-secret
        - name: MONGO_URL
          valueFrom:
            secretKeyRef: 
              name: mongodb-url
              key: curi-secret
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef: 
              name: aws-accesskey
              key: curi-secret
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef: 
              name: aws-secretkey
              key: curi-secret
        - name: AWS_SQS_QUEUE_NAME
          valueFrom:
            secretKeyRef: 
              name: loglevel-secret
              key: curi-secret
        - name: AWS_SQS_QUEUE_URL
          valueFrom:
            secretKeyRef: 
              name: aws-sqs-name
              key: curi-secret
        - name: AWS_REGION
          value: ap-northeast-2
        - name: DDL_AUTO
          value: update
        - name: ENVIRONMENT
          value: cloud

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 768Mi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]