apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/spring/curi-scheduler
  newName: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/spring/curi-scheduler
  newTag: 300ae00a
resources:
- ../../base
patches:
- path: scheduler-deployment-patch.yaml
- path: scheduler-service-patch.yaml
  target:
    namespace: eks-work
