apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-app
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: scheduler-app
  template:
    metadata:
      labels:
        app: scheduler-app
    spec:
      containers:
      - name: scheduler-app
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi