apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  namespace: default
  labels:
    env: product
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi