apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
  labels:
    env: product
spec:
  selector:
    app: auth-app
