apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: ai-app
  template:
    spec:
      containers:
      - name: ai-app
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi