apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/flask/ai
  newName: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/flask/ai
  newTag: 393472c9
resources:
- ../../base
patches:
- path: ai-deployment-patch.yaml
- path: ai-service-patch.yaml
  target:
    namespace: eks-work
