apiVersion: v1
kind: Service
metadata:
  name: scheduler-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
spec:
  type: NodePort
  selector:
    app: scheduler-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081