apiVersion: v1
kind: Service
metadata:
  name: back-office-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
spec:
  type: NodePort
  selector:
    app: back-office-app
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3000
