apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-office-app
  labels:
    app: back-office-app
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: back-office-app
  template:
    metadata:
      labels:
        app: back-office-app
    spec:
      containers:
      - name: back-office-app
        image: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/next/curi-back-office:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 768Mi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]