apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-office-app
  labels:
    app: back-office-app
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: back-office-app
  template:
    metadata:
      labels:
        app: back-office-app
    spec:
      containers:
      - name: back-office-app
        image: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/next/curi-back-office:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef: 
              key: firebase-api-key
              name: curi-secret
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef: 
              key: firebase-auth-domain
              name: curi-secret
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef: 
              key: firebase-project-id
              name: curi-secret
        - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef: 
              key: firebase-storage-bucket
              name: curi-secret
        - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef: 
              key: firebase-messaging-sender-id
              name: curi-secret
        - name: NEXT_PUBLIC_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef: 
              key: firebase-app-id
              name: curi-secret
        - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
          valueFrom:
            secretKeyRef: 
              key: firebase-measurement-id
              name: curi-secret
        - name: NEXT_PUBLIC_RESOURSE_API_URL
          valueFrom:
            secretKeyRef: 
              key: resource-api-url
              name: curi-secret
        - name: NEXT_PUBLIC_AUTH_API_URL
          valueFrom:
            secretKeyRef: 
              key: auth-api-url
              name: curi-secret
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 768Mi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]