apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/next/curi-demo
  newName: 332543631386.dkr.ecr.ap-northeast-2.amazonaws.com/next/curi-demo
  newTag: 534dcfba
resources:
- ../../base
patches:
- path: demo-deployment-patch.yaml
- path: demo-service-patch.yaml
  target:
    namespace: eks-work
