apiVersion: v1
kind: Service
metadata:
  name: view-app-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/all"
  labels:
    env: product
spec:
  selector:
    app: view-app
