apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.curiboard.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: backend-app-service
              port: 
                number: 8080
  - host: auth.curiboard.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "auth-app-service"
              port:
                number: 8000
  - host: demo.curiboard.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: demo-app-service
              port: 
                number: 3000
  - host: asdklahro234ksachx09821ohed0821-asdhu2h34oisfoiausd12asd.curiboard.com
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: argocd-server
              port: 
                name: https